# This Cloud Build file builds a Docker image and deploys it to GKE using Helm (DEV).

steps:
  # 1. Calculate the next semantic version tag
  - id: "Calculate New Tag"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        # Use dev repo/image name
        LATEST_TAG=$$(gcloud artifacts docker tags list europe-west2-docker.pkg.dev/$PROJECT_ID/my-docker-repo/${_APP_NAME} --format="value(TAG)" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$$' | sort -V | tail -n 1 || true)
        
        if [ -z "$$LATEST_TAG" ]; then
          NEW_TAG="0.0.1"
        else
          MAJOR=$$(echo $$LATEST_TAG | cut -d. -f1)
          MINOR=$$(echo $$LATEST_TAG | cut -d. -f2)
          PATCH=$$(echo $$LATEST_TAG | cut -d. -f3)
          NEW_PATCH=$$((PATCH + 1))
          NEW_TAG="$$MAJOR.$$MINOR.$$NEW_PATCH"
        fi
        
        echo "Calculated new tag: $$NEW_TAG"
        echo $$NEW_TAG > /workspace/tag.txt

  # 2. Build the Docker image
  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        NEW_TAG=$$(cat /workspace/tag.txt)
        echo "--- Building Docker image with tag: $$NEW_TAG ---"
        docker build -t "europe-west2-docker.pkg.dev/$PROJECT_ID/my-docker-repo/${_APP_NAME}:$$NEW_TAG" -f Dockerfile .
    waitFor: ["Calculate New Tag"]

  # 3. Push the container image
  - id: "Push Docker Image to GAR"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        NEW_TAG=$$(cat /workspace/tag.txt)
        docker push "europe-west2-docker.pkg.dev/$PROJECT_ID/my-docker-repo/${_APP_NAME}:$$NEW_TAG"
    waitFor: ["Build Docker Image"]

  # 4. Deploy to GKE using Helm
  - id: "Deploy to GKE"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -ex
        HELM_VERSION=v3.15.2
        curl -sSL https://get.helm.sh/helm-$${HELM_VERSION}-linux-amd64.tar.gz -o helm.tar.gz
        tar -zxvf helm.tar.gz
        
        NEW_TAG=$$(cat /workspace/tag.txt)
        echo "--- Deploying to GKE (Dev) with Helm, using image tag: $$NEW_TAG ---"
        
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_CLUSTER_LOCATION} --project $PROJECT_ID
        
        # Create/Update dev secret (chat-api-secrets-dev)
        kubectl create secret generic chat-api-secrets-dev \
          --from-literal=DB_PASSWORD="$$(gcloud secrets versions access latest --secret=db-pass-nvd11 --project=$PROJECT_ID)" \
          --from-literal=GEMINI_API_KEY="$$(gcloud secrets versions access latest --secret=gemini-api-key --project=$PROJECT_ID)" \
          --from-literal=DEEPSEEK_API_KEY="$$(gcloud secrets versions access latest --secret=deepseek-api-key --project=$PROJECT_ID)" \
          --dry-run=client -o yaml | kubectl apply -f -
        
        # Fetch the Auth0 Client ID for docs from Secret Manager
        DOCS_CLIENT_ID=$$(gcloud secrets versions access latest --secret=clien-id-auth0-askc-dev --project=$PROJECT_ID)

        # Run Helm deployment, overriding the client ID placeholder
        ./linux-amd64/helm upgrade --install ${_APP_NAME} ./helm \
          -f ./helm/values-chat-api-svc-dev.yaml \
          --set image.tag=$$NEW_TAG \
          --set-string "extraEnv[4].value=$$DOCS_CLIENT_ID" \
          --namespace default
    waitFor: ["Push Docker Image to GAR"]

logsBucket: gs://jason-hsbc_cloudbuild/logs/
options:
  logging: GCS_ONLY
serviceAccount: "projects/jason-hsbc/serviceAccounts/terraform@jason-hsbc.iam.gserviceaccount.com"

substitutions:
  _APP_NAME: askc-bak-svc-dev
  _CLUSTER_NAME: my-cluster2
  _CLUSTER_LOCATION: europe-west2
